---
language: python
python:
  - 3.6
cache: pip

install:
  - pip install -r requirements.txt

script:
  - yamllint .
  - ansible-lint -v

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
