---
services: docker

language: python
python:
  - 3.6
cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - cd ..
  - mv ansible-role-grub hadrienpatte.grub
  - cd hadrienpatte.grub

script:
  - molecule lint

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
