---
dist: bionic
language: python
python: 3.8
cache: pip

stages:
  - lint

jobs:
  include:
    - name: yamllint
      stage: lint
      install:
        - pip install yamllint
      script:
        - yamllint .

    - name: ansible-lint
      stage: lint
      install:
        - pip install ansible-lint
      script:
        - ansible-lint -v

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
